### ISSUE TITLE
Platformio fail to build mbedtls in ESP-IDF and Arduino

### ISSUE THREAD

**Issue by MisterXYZ83** [J-Rios/uTLGBotLib#1]
Hello,

thanks for this library, i would like to use for a little project in my home. I have a problem with the build process...i get many "undeclaration" errors like this:

`lib\multihttpsclient\mbedtls\library\aes.c:1844:20: error: 'MBEDTLS_ERR_PLATFORM_FEATURE_UNSUPPORTED' undeclared (first use in this function)`

and many others...but the header files are included correctly, i didn't touch the sources yet; i just commented in platformio.ini the unused sections (native and arduino, i'm working on ESP32 platform).

thanks for help!

**Comment by J-Rios** [comment]
Hi,

It seems esp-idf build is broken due lastest refactorization changes related to multihttpsclient library. Platformio build process try to compile multihttpsclient/mbedtls in esp-idf and arduino enviorenment instead used framework specific mbedtls, and it's happen even mbedtls sources are not included in project sources...

I will take a look about it, Platformio build when there is a library inside another one, and the name of the library is same as one existing in actual framework is a madness.

**Comment by MisterXYZ83** [comment]
thanks!
i will follow your repository for future updates! :D

Il giorno dom 6 ott 2019 alle ore 20:41 Jose <notifications@github.com> ha
scritto:

**Comment by J-Rios** [comment]
Ok, now it's fixed ;)

I have to add a Platformio "extra_script" into multihttpsclient library, that runs before lib build, to exclude mbedtls directory from be compiled in esp-idf and arduino builds.

Please remove and clone again lastest version of uTLGBot library and check it.

**Comment by MisterXYZ83** [comment]
thanks jose!
i will try as soon as possible :)

Il giorno dom 6 ott 2019 alle ore 21:52 Jose <notifications@github.com> ha
scritto:
