### ISSUE TITLE
How to display utf-8 character?  like chinese

### ISSUE THREAD

**Issue by terrywu5** [J-Rios/uTLGBotLib#2]
I use the example "show_received_messages" , I send message with telegram
English word display is normal, but when I type in Chinese "你好" it show "\u4f60\u597d"
How to display utf-8 character?
-----------------------------------------
Received message.
  From chat ID: 1048xxxxx
  From chat type: private
  From chat alias: terxxxxx
  From chat name: Terxxxxx
  From chat title: 
  From chat where not all members are admins.
  From user ID: 1048xxxxx
  From user alias: @terxxxxx
  From user name: Terxxxxx
  From user with language code: zh-hans
  From user that is not a Bot.
  Message ID: 630
  Message sent date (UNIX epoch time): 1590229558l
  Text: \u4f60\u597d
-----------------------------------------

and I test serial print utf-8 code, it can print Chinese word

            Serial.println("");
            Serial.println("WiFi connected");
            Serial.print("IP address: ");
            Serial.println(WiFi.localIP());
            char mesg[50] = "\u65e5\u5b89\u4f60\u597d"; //日安你好
            Serial.println(mesg);
            wifi_connected = true;
--------------------------------------------------------
WiFi connected
IP address: 192.168.0.144
日安你好

**Comment by J-Rios** [comment]
Seems like a utf-8 encode problem, or how to Serial.print encoded data... not related to uTLGBotLib.

About why it works when you use:
`char mesg[50] = "\u65e5\u5b89\u4f60\u597d";`

The IDE could interpret and encode this, so _mesg_ doesn't contains what you expect (C++ handle char* like bytes, it doesn't know anything about text codification).
